//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectFourEntities : DbContext
    {
        public ConnectFourEntities()
            : base("name=ConnectFourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrators> Administrators { get; set; }
        public DbSet<FriendRequests> FriendRequests { get; set; }
        public DbSet<Friends> Friends { get; set; }
        public DbSet<Matches> Matches { get; set; }
        public DbSet<Players> Players { get; set; }
        public DbSet<PlayersMatch> PlayersMatch { get; set; }
    }
}
