//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FriendRequests
    {
        public int requestID { get; set; }
        public int sender { get; set; }
        public int receiver { get; set; }
        public Nullable<System.DateTime> sent { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
