//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Matches
    {
        public Matches()
        {
            this.PlayersMatch = new ObservableCollection<PlayersMatch>();
        }
    
        public int gameID { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public Nullable<int> winnerID { get; set; }
        public Nullable<int> url { get; set; }
    
        public virtual ObservableCollection<PlayersMatch> PlayersMatch { get; set; }
    }
}
