//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Players
    {
        public Players()
        {
            this.FriendRequests = new ObservableCollection<FriendRequests>();
            this.Friends = new ObservableCollection<Friends>();
            this.PlayersMatch = new ObservableCollection<PlayersMatch>();
        }
    
        public int playerID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string nickname { get; set; }
        public string status { get; set; }
        public Nullable<int> coins { get; set; }
        public Nullable<int> matches { get; set; }
        public Nullable<int> winnerScore { get; set; }
        public string biography { get; set; }
        public Nullable<System.DateTime> lastConnection { get; set; }
        public Nullable<System.DateTime> registration { get; set; }
        public string profileImageName { get; set; }
    
        public virtual ObservableCollection<FriendRequests> FriendRequests { get; set; }
        public virtual ObservableCollection<Friends> Friends { get; set; }
        public virtual ObservableCollection<PlayersMatch> PlayersMatch { get; set; }
    }
}
